global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['10.0.0.101:9093']

rule_files:
  - "node_down.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['172.18.0.1:9090']

  - job_name: 'node'
    scrape_interval: 8s
    static_configs:
    - targets: ['172.18.0.1:9100', '172.18.0.1:9100']

  - job_name: 'cadvisor'
    scrape_interval: 8s
    static_configs:
    - targets: ['172.18.0.1:8088', '172.18.0.1:8088']