 services:
   rabbitmq1:
     image: rabbitmq:3.12.6-management
     container_name: rabbitmq1
     hostname: rabbitmq1
     environment:
       RABBITMQ_DEFAULT_VHOST: /
       RABBITMQ_ERLANG_COOKIE: "SECRETCOOKIE"
       RABBITMQ_DEFAULT_USER: admin
       RABBITMQ_DEFAULT_PASS: admin
       RABBITMQ_PLUGINS_DIR: '/plugins:/myplugins'
     ports:
       - "5672:5672"
       - "15672:15672"
     volumes:
       - ./rabbitmq/rabbitmq1/data:/var/lib/rabbitmq
       - ./rabbitmq/rabbitmq1/myplugins:/myplugins
     networks:
       - rabbitmq_net

   rabbitmq2:
     image: rabbitmq:3.12.6-management
     container_name: rabbitmq2
     hostname: rabbitmq2
     environment:
       RABBITMQ_DEFAULT_VHOST: /
       RABBITMQ_ERLANG_COOKIE: "SECRETCOOKIE"
       RABBITMQ_DEFAULT_USER: admin
       RABBITMQ_DEFAULT_PASS: admin
       RABBITMQ_PLUGINS_DIR: '/plugins:/myplugins'
     ports:
       - "5673:5672"
       - "15673:15672"
     volumes:
       - ./rabbitmq/rabbitmq2/data:/var/lib/rabbitmq
       - ./rabbitmq/rabbitmq2/myplugins:/myplugins
     networks:
       - rabbitmq_net
     depends_on:
       - rabbitmq1

   rabbitmq3:
     image: rabbitmq:3.12.6-management
     container_name: rabbitmq3
     hostname: rabbitmq3
     environment:
       RABBITMQ_DEFAULT_VHOST: /
       RABBITMQ_ERLANG_COOKIE: "SECRETCOOKIE"
       RABBITMQ_DEFAULT_USER: admin
       RABBITMQ_DEFAULT_PASS: admin
       RABBITMQ_PLUGINS_DIR: '/plugins:/myplugins'
     ports:
       - "5674:5672"
       - "15674:15672"
     volumes:
       - ./rabbitmq/rabbitmq3/data:/var/lib/rabbitmq
       - ./rabbitmq/rabbitmq3/myplugins:/myplugins
     networks:
       - rabbitmq_net
     depends_on:
       - rabbitmq2


 networks:
   rabbitmq_net:
