networks:
  kafka_zk_network:
    external: true
services:
  zk-standalone:
    image: zookeeper:latest
    restart: always
    container_name: zk-standalone
    hostname: zk-standalone
    ports:
      - "2181:2181"
    networks:
      - kafka_zk_network
    volumes:
      - ./zk-standalone/data:/data
      - ./zk-standalone/datalog:/datalog
      - /etc/localtime:/etc/localtime

  kafka1:
    image: 'bitnami/kafka:3.8.1'
    container_name: kafka1
    hostname: kafka1
    networks:
      - kafka_zk_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk-standalone:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.20.128:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zk-standalone
  kafka2:
    image: 'bitnami/kafka:3.8.1'
    container_name: kafka2
    hostname: kafka2
    networks:
      - kafka_zk_network
    ports:
      - '9093:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk-standalone:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.20.128:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zk-standalone

  kafka3:
    image: 'bitnami/kafka:3.8.1'
    container_name: kafka3
    hostname: kafka3
    networks:
      - kafka_zk_network
    ports:
      - '9094:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk-standalone:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.20.128:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zk-standalone
